name: youtube_screens
version: 1.0.0+1
description: Clone Youtube Screens With Flutter
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_lorem: ^2.0.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get: 4.6.6
  google_fonts: 6.1.0
  readmore: ^2.2.0
  timeago: ^3.6.1

dev_dependencies:
  build_runner: ^2.4.8
  # gen image svg fonts
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/jpg/
    - assets/svg/
    - assets/webp/

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true

  colors:
    inputs:
      - assets/colors/colors.xml
